<a href="https://colab.research.google.com/github/AnnaGabriela03/23.1_trilha_for_code/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# im bacc bitches!!
#numpy é uma, bibliotea em C
import numpy as np
lista_python = [1,2,3]
numpy_array = np.array([[1,2,3], [2,3,4], [1,2,3]])
numpy_array

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3]])

In [30]:
det_A = np.linalg.det(numpy_array)
det_A

0.0

In [18]:
numpy_array = np.append(numpy_array, [1])
numpy_array

array([1, 2, 4, 1, 1, 1])

In [23]:
array2 = np.linspace(1, 10, 10)
array2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
numpy_array * 3
# prod vetorial

array([ 3,  6, 12,  3,  3,  3])

In [27]:
# array3 = np.array()
# numpy_array.dot()
# # tem td um pacote de algelin etc
# A_inv = np.linalg.inv(A)
# det_A = np.linalg.det(A)
# # vetores e mt mais rs